# Use Docker-based container (instead of OpenVZ)
#sudo: false

#cache:
#  directories:
#    - $HOME/.ivy2/cache

    # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
    # which fortunately corresponds to current scalaz settings.
    # The line below can be used to cache a given sbt version.
    - $HOME/.sbt/launchers/0.13.7

    # The line below is used to cache the scala version used by the build
    # job, as these versions might be replaced after a Travis CI build
    # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala

scala:
  - 2.10.4

jdk:
  - openjdk6

script:
  - "sbt -J-XX:PermSize=256M -J-XX:MaxPermSize=512M -J-Xss1024K -J-Xms512M -J-Xmx1024M -J-XX:+CMSClassUnloadingEnabled -J-XX:+UseCodeCacheFlushing -J-XX:+UseConcMarkSweepGC -J-XX:+CMSIncrementalPacing -J-XX:+DoEscapeAnalysis $TASKS"

  # Tricks to avoid unnecessary cache updates
#  - find $HOME/.sbt -name "*.lock" | xargs rm
#  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

env:
  - TASKS=test
  - TASKS=integrationTestsWithoutOffline
  - TASKS=echo-cotests/test

notifications:
  flowdock: 2eb8fdbb08ad2e595a21edea64252a22